CXX = g++
CXXFLAGS = -g -Wall -std=c++17 $(INCLUDE)
CC = g++
SOURCEDIR=../src
INCLUDE=-I $(SOURCEDIR)

TARGETS = fib fib_nobase

default: $(TARGETS)

fib:

fib.o:

fib_nobase:

fib_nobase.o:

main_tester:

main_tester.o:

clean:
	rm -rf $(TARGETS) a.out *.o
